server:
  port: 8082

spring:
  application:
    name: UserService
  datasource:
    url: jdbc:mariadb://192.168.93.128:3306/liveload?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mari33#06adb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8180/eureka/,http://localhost:8181/eureka/