server:
  port: 8181

spring:
  application:
    name: EurekaService02

eureka:
  instance:
    hostname: eureka02
    instance-id: ${spring.application.name}
  client:
    fetch-registry: false
#    register-with-eureka: false
    service-url:
      defaultZone: http://eureka01:8180/eureka/
